#!/usr/bin/env python
# Rhymes with bake, rake, and make
# This is the "execution" script. By default it will read from a "snakefile". 
# Requires buildit to be installed.

import os
import sys

from optparse import OptionGroup
from bit.instance import bit

if __name__ == '__main__':
    options = OptionGroup(bit.parser)
    options.add_option('-f', '--file', dest='file_name', 
                      default='bitfile', help='run from FILE_NAME')
    bit.parser.add_option_group(options)
    options, args = bit.parser.parse_args()
    try:
        with open(options.file_name) as bitfile:
            run_string = 'from bit import *\n{0}'.format(''.join(bitfile)) 
            run_string = '{0}\nbit.run()'.format(run_string)
            exec(run_string)
    except IOError:
        print('Could not open file: {0}'.format(options.file_name))

